import { describe, it, expect } from 'vitest';
import { readFile } from 'fs/promises';
import { join } from 'path';
import {
  generateClaudeCodePM,
  generateCopilotPM,
  generateClaudeCodeAgent,
  generateCopilotAgent,
  extractRoutingLogic,
  AGENT_NAMES,
} from '../../prompts.js';

// --- 8.1: Agent body identity after frontmatter stripping ---
describe('prompt body parity across platforms', () => {
  it('agent body is identical after frontmatter stripping', () => {
    for (const agent of AGENT_NAMES) {
      const claudeBody = generateClaudeCodeAgent(agent);
      const copilotFull = generateCopilotAgent(agent);
      // Strip YAML frontmatter from Copilot version
      const copilotBody = copilotFull.replace(/^---\n[\s\S]*?\n---\n\n?/, '');
      expect(copilotBody).toBe(claudeBody);
    }
  });
});

// --- 8.2: PM routing logic identity ---
describe('PM routing logic identity', () => {
  it('routing logic is identical after spawn syntax normalization', () => {
    const claudeLogic = extractRoutingLogic(generateClaudeCodePM());
    const copilotLogic = extractRoutingLogic(generateCopilotPM());
    expect(claudeLogic).toBe(copilotLogic);
  });
});

// --- 8.3: Copilot frontmatter validation ---
describe('Copilot frontmatter validation', () => {
  it('all thin agents have user-invokable: false', () => {
    for (const agent of AGENT_NAMES) {
      const prompt = generateCopilotAgent(agent);
      const frontmatter = prompt.match(/^---\n([\s\S]*?)\n---/)?.[1] ?? '';
      expect(frontmatter).toContain('user-invokable: false');
    }
  });

  it('all agents declare required MCP tools in frontmatter', () => {
    const requiredTools = [
      'specflow_context',
      'specflow_state',
      'specflow_validate',
      'specflow_codebase',
      'specflow_impact',
    ];

    for (const agent of AGENT_NAMES) {
      const prompt = generateCopilotAgent(agent);
      const frontmatter = prompt.match(/^---\n([\s\S]*?)\n---/)?.[1] ?? '';

      for (const tool of requiredTools) {
        expect(frontmatter).toContain(`- ${tool}`);
      }
    }
  });

  it('Copilot agents include editor tools', () => {
    for (const agent of AGENT_NAMES) {
      const prompt = generateCopilotAgent(agent);
      expect(prompt).toContain('- editFiles');
      expect(prompt).toContain('- fetchWebpage');
    }
  });
});

// --- 8.4: PM agents list ↔ .github/agents/ file cross-reference ---
describe('PM agents list cross-reference', () => {
  it('Copilot PM frontmatter lists all defined agents', () => {
    const pmPrompt = generateCopilotPM();
    const frontmatter = pmPrompt.match(/^---\n([\s\S]*?)\n---/)?.[1] ?? '';

    for (const agent of AGENT_NAMES) {
      expect(frontmatter).toContain(`sf-${agent}`);
    }
  });

  it('every AGENT_NAMES entry has a corresponding agent generator', () => {
    for (const agent of AGENT_NAMES) {
      const claudePrompt = generateClaudeCodeAgent(agent);
      expect(claudePrompt.length).toBeGreaterThan(0);
      expect(claudePrompt).toContain('specflow_context');

      const copilotPrompt = generateCopilotAgent(agent);
      expect(copilotPrompt).toContain(`name: sf-${agent}`);
    }
  });
});

// --- 8.5: Agent name resolution ---
describe('agent name resolution in spawn calls', () => {
  it('Claude Code PM Task() calls reference valid agents', () => {
    const pmPrompt = generateClaudeCodePM();

    // All agent names referenced in Task() calls should be valid
    // The PM uses Task() syntax for spawning
    expect(pmPrompt).toContain('Task(');
    expect(pmPrompt).not.toContain('runSubagent(');
  });

  it('Copilot PM runSubagent() calls reference valid agent names', () => {
    const pmPrompt = generateCopilotPM();

    // Extract all agent names from runSubagent() calls
    const agentRefs = [...pmPrompt.matchAll(/agent="(sf-[\w-]+)"/g)].map(m => m[1]);

    // Each referenced agent should correspond to a known agent name
    for (const ref of agentRefs) {
      const name = ref.replace('sf-', '');
      // The name should either be in AGENT_NAMES or be a known dynamic reference
      const isKnown = AGENT_NAMES.includes(name as typeof AGENT_NAMES[number])
        || name.startsWith('<'); // Template placeholder like <agent>
      expect(isKnown).toBe(true);
    }
  });
});

// --- 8.6: MCP config key validation ---
describe('MCP config key validation', () => {
  it('.mcp.json structure uses mcpServers key', () => {
    // This tests the structure generated by createMcpConfig
    const config: Record<string, unknown> = {};
    const serverKey = 'mcpServers';
    if (!config[serverKey]) config[serverKey] = {};
    const servers = config[serverKey] as Record<string, unknown>;
    servers['specflow'] = {
      command: 'npx',
      args: ['specflow', 'serve'],
    };

    expect(config).toHaveProperty('mcpServers');
    expect(config).not.toHaveProperty('servers');
    expect((config.mcpServers as Record<string, unknown>).specflow).toBeDefined();
  });

  it('.vscode/mcp.json structure uses servers key', () => {
    const config: Record<string, unknown> = {};
    const serverKey = 'servers';
    if (!config[serverKey]) config[serverKey] = {};
    const servers = config[serverKey] as Record<string, unknown>;
    servers['specflow'] = {
      command: 'npx',
      args: ['specflow', 'serve'],
    };

    expect(config).toHaveProperty('servers');
    expect(config).not.toHaveProperty('mcpServers');
    expect((config.servers as Record<string, unknown>).specflow).toBeDefined();
  });

  it('both configs use identical command and args', () => {
    const command = 'npx';
    const args = ['specflow', 'serve'];

    // Claude Code config
    const claudeConfig = { mcpServers: { specflow: { command, args } } };
    // Copilot config
    const copilotConfig = { servers: { specflow: { command, args } } };

    expect(claudeConfig.mcpServers.specflow.command).toBe(copilotConfig.servers.specflow.command);
    expect(claudeConfig.mcpServers.specflow.args).toEqual(copilotConfig.servers.specflow.args);
  });
});

// --- 8.7: No remaining template placeholders ---
describe('placeholder resolution', () => {
  it('Claude Code PM has no unresolved {{SPAWN}} placeholders', () => {
    const prompt = generateClaudeCodePM();
    expect(prompt).not.toContain('{{SPAWN}}');
    expect(prompt).not.toContain('{{SPAWN:');
    expect(prompt).not.toMatch(/\{\{[^}]+\}\}/);
  });

  it('Copilot PM has no unresolved {{SPAWN}} placeholders', () => {
    const prompt = generateCopilotPM();
    expect(prompt).not.toContain('{{SPAWN}}');
    expect(prompt).not.toContain('{{SPAWN:');
    expect(prompt).not.toMatch(/\{\{[^}]+\}\}/);
  });

  it('no agent prompts contain literal <agent> or <phase> in spawn calls', () => {
    // Agent prompts themselves should not have template placeholders
    for (const agent of AGENT_NAMES) {
      const claude = generateClaudeCodeAgent(agent);
      const copilot = generateCopilotAgent(agent);

      // Thin agents don't contain spawn calls at all
      expect(claude).not.toContain('{{SPAWN');
      expect(copilot).not.toContain('{{SPAWN');
    }
  });
});

// --- 8.8: Spawn syntax isolation ---
describe('spawn syntax isolation', () => {
  it('Claude Code prompts never contain runSubagent', () => {
    const pmPrompt = generateClaudeCodePM();
    expect(pmPrompt).not.toContain('runSubagent(');

    for (const agent of AGENT_NAMES) {
      const agentPrompt = generateClaudeCodeAgent(agent);
      expect(agentPrompt).not.toContain('runSubagent(');
    }
  });

  it('Copilot prompts never contain Task(subagent_type', () => {
    const pmPrompt = generateCopilotPM();
    expect(pmPrompt).not.toContain('Task(subagent_type=');
    expect(pmPrompt).not.toContain('Task(subagent_type');

    for (const agent of AGENT_NAMES) {
      const agentPrompt = generateCopilotAgent(agent);
      expect(agentPrompt).not.toContain('Task(subagent_type=');
    }
  });
});
