#!/usr/bin/env bash
set -euo pipefail

# Ticket Creator - Create tickets from approved specs
# Usage: scripts/ticket-creator.sh [command] <feature-name> [options]
# Reads spec from .specflow/specs/{feature}/spec.md
# Creates epic + stories in configured tracker

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/tracker-adapter.sh"

SPECFLOW_DIR=".specflow"
SPECS_DIR="$SPECFLOW_DIR/specs"
TICKETS_DIR="$SPECFLOW_DIR/tickets"
LOG_FILE="$SPECFLOW_DIR/ticket-creation.log"

# Max body length for GitHub (leave room for truncation message)
MAX_BODY_LENGTH=60000

# =============================================================================
# Helper Functions
# =============================================================================

_log_creation() {
    local feature="$1"
    local message="$2"
    local timestamp
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    mkdir -p "$(dirname "$LOG_FILE")"
    echo "$timestamp | $feature | $message" >> "$LOG_FILE"
}

_spec_exists() {
    local feature="$1"
    local spec_file="$SPECS_DIR/$feature/spec.md"
    [ -f "$spec_file" ]
}

_read_spec() {
    local feature="$1"
    local spec_file="$SPECS_DIR/$feature/spec.md"
    cat "$spec_file"
}

_extract_section() {
    # Extract a markdown section by header
    # Arguments: content, section_name
    local content="$1"
    local section="$2"

    echo "$content" | awk -v section="$section" '
        BEGIN { found = 0; level = 0 }
        /^##+ / {
            if (found && level > 0) {
                # Check if new header is same or higher level
                curr_level = gsub(/#/, "#", $1)
                if (curr_level <= level) exit
            }
            if (index($0, section) > 0) {
                found = 1
                level = gsub(/#/, "#", $1)
                next
            }
        }
        found { print }
    '
}

# =============================================================================
# Core Functions
# =============================================================================

extract_acceptance_criteria() {
    # Parse acceptance criteria section from spec
    # Returns criteria as newline-separated list
    local spec_content="$1"

    local criteria_section
    criteria_section=$(_extract_section "$spec_content" "Acceptance Criteria")

    # Extract checkbox items
    echo "$criteria_section" | grep -E '^\s*-\s*\[[ x]\]' | sed 's/^\s*-\s*\[[ x]\]\s*//'
}

count_acceptance_criteria() {
    local spec_content="$1"
    local criteria
    criteria=$(extract_acceptance_criteria "$spec_content")
    echo "$criteria" | grep -c '.' || echo "0"
}

build_epic_body() {
    # Build epic body with full spec content embedded
    # Arguments: feature_name
    local feature="$1"
    local spec_file="$SPECS_DIR/$feature/spec.md"
    local spec_content
    spec_content=$(cat "$spec_file")

    local body=""

    # Title
    body+="# Feature: $feature"$'\n\n'

    # Overview section
    local overview
    overview=$(_extract_section "$spec_content" "Overview")
    if [ -n "$overview" ]; then
        body+="## Overview"$'\n'
        body+="$overview"$'\n\n'
    fi

    # Security Assessment section
    local security
    security=$(_extract_section "$spec_content" "Security")
    if [ -n "$security" ]; then
        body+="## Security Assessment"$'\n'
        body+="$security"$'\n\n'
    fi

    # Cost Estimate section
    local cost
    cost=$(_extract_section "$spec_content" "Cost")
    if [ -n "$cost" ]; then
        body+="## Cost Estimate"$'\n'
        body+="$cost"$'\n\n'
    fi

    # Test Scenarios section
    local tests
    tests=$(_extract_section "$spec_content" "Test")
    if [ -n "$tests" ]; then
        body+="## Test Scenarios"$'\n'
        body+="$tests"$'\n\n'
    fi

    # Acceptance Criteria section
    local criteria
    criteria=$(_extract_section "$spec_content" "Acceptance Criteria")
    if [ -n "$criteria" ]; then
        body+="## Acceptance Criteria"$'\n'
        body+="$criteria"$'\n\n'
    fi

    # Add footer
    body+="---"$'\n'
    body+="*Generated by SpecFlow from: $spec_file*"

    # Truncate if too long
    if [ ${#body} -gt $MAX_BODY_LENGTH ]; then
        body="${body:0:$MAX_BODY_LENGTH}"$'\n\n'
        body+="---"$'\n'
        body+="*[Truncated - See full spec: $spec_file]*"
    fi

    echo "$body"
}

extract_pillar_labels() {
    # Extract pillar labels based on spec content
    # Returns comma-separated labels
    local spec_content="$1"
    local labels=""

    # Check for security section
    if echo "$spec_content" | grep -qi "security\|stride\|threat"; then
        labels+="security,"
    fi

    # Check for cost section
    if echo "$spec_content" | grep -qi "cost\|estimate\|monthly"; then
        labels+="cost,"
    fi

    # Check for test section
    if echo "$spec_content" | grep -qi "test\|scenario\|gherkin\|given.*when.*then"; then
        labels+="testing,"
    fi

    # Remove trailing comma
    echo "${labels%,}"
}

determine_stories() {
    # Determine what stories to create based on spec content
    # Returns JSON array of story definitions
    local spec_content="$1"
    local feature="$2"

    local stories="[]"
    local criteria
    criteria=$(extract_acceptance_criteria "$spec_content")
    local total_criteria
    total_criteria=$(echo "$criteria" | grep -c '.' || echo "0")

    # Heuristic: Check content for work type indicators
    local has_backend=false
    local has_frontend=false

    if echo "$spec_content" | grep -qiE "api|endpoint|backend|server|database|rest|graphql"; then
        has_backend=true
    fi

    if echo "$spec_content" | grep -qiE "ui|frontend|button|form|page|component|css|react|vue"; then
        has_frontend=true
    fi

    # Distribute criteria across stories
    local backend_criteria=""
    local frontend_criteria=""
    local test_criteria=""
    local idx=0

    while IFS= read -r criterion; do
        [ -z "$criterion" ] && continue
        if echo "$criterion" | grep -qiE "api|endpoint|database|auth|server"; then
            backend_criteria+="$criterion"$'\n'
        elif echo "$criterion" | grep -qiE "ui|button|display|show|view|form"; then
            frontend_criteria+="$criterion"$'\n'
        else
            test_criteria+="$criterion"$'\n'
        fi
        idx=$((idx + 1))
    done <<< "$criteria"

    # Story 1: Backend (if applicable)
    if [ "$has_backend" = true ] || [ -n "$backend_criteria" ]; then
        local backend_count
        backend_count=$(echo "$backend_criteria" | grep -c '.' || echo "0")
        [ "$backend_count" -eq 0 ] && backend_count=2
        local backend_points
        backend_points=$(_calculate_story_points "$backend_count")

        stories=$(echo "$stories" | jq \
            --arg title "Story: Backend implementation for $feature" \
            --arg type "backend" \
            --argjson points "$backend_points" \
            --arg criteria "$backend_criteria" \
            '. + [{title: $title, type: $type, story_points: $points, criteria: $criteria}]')
    fi

    # Story 2: Frontend (if applicable)
    if [ "$has_frontend" = true ] || [ -n "$frontend_criteria" ]; then
        local frontend_count
        frontend_count=$(echo "$frontend_criteria" | grep -c '.' || echo "0")
        [ "$frontend_count" -eq 0 ] && frontend_count=2
        local frontend_points
        frontend_points=$(_calculate_story_points "$frontend_count")

        stories=$(echo "$stories" | jq \
            --arg title "Story: Frontend implementation for $feature" \
            --arg type "frontend" \
            --argjson points "$frontend_points" \
            --arg criteria "$frontend_criteria" \
            '. + [{title: $title, type: $type, story_points: $points, criteria: $criteria}]')
    fi

    # Story 3: Testing (always)
    local test_count
    test_count=$(echo "$test_criteria" | grep -c '.' || echo "0")
    [ "$test_count" -eq 0 ] && test_count=2
    local test_points
    test_points=$(_calculate_story_points "$test_count")

    stories=$(echo "$stories" | jq \
        --arg title "Story: Testing and verification for $feature" \
        --arg type "testing" \
        --argjson points "$test_points" \
        --arg criteria "$test_criteria" \
        '. + [{title: $title, type: $type, story_points: $points, criteria: $criteria}]')

    echo "$stories"
}

build_story_body() {
    # Build story body with subset of acceptance criteria
    # Arguments: story_json, epic_number
    local story_json="$1"
    local epic_number="$2"

    local title criteria story_points
    title=$(echo "$story_json" | jq -r '.title')
    criteria=$(echo "$story_json" | jq -r '.criteria // ""')
    story_points=$(echo "$story_json" | jq -r '.story_points')

    local body=""
    body+="# $title"$'\n\n'
    body+="## Description"$'\n'
    body+="Implementation story generated from SpecFlow spec."$'\n\n'
    body+="## Acceptance Criteria"$'\n'

    # Format criteria as checkboxes
    while IFS= read -r criterion; do
        [ -z "$criterion" ] && continue
        body+="- [ ] $criterion"$'\n'
    done <<< "$criteria"

    body+=$'\n'
    body+="## Parent Epic"$'\n'
    body+="#$epic_number"$'\n\n'
    body+="---"$'\n'
    body+="*Story points: $story_points*"$'\n'
    body+="*Generated by SpecFlow*"

    echo "$body"
}

create_epic_from_spec() {
    # Create epic from approved spec
    # Arguments: feature_name
    # Returns: JSON with epic details
    local feature="$1"

    if ! _spec_exists "$feature"; then
        echo "Error: Spec not found: $SPECS_DIR/$feature/spec.md" >&2
        return 1
    fi

    local spec_content
    spec_content=$(_read_spec "$feature")

    # Build epic body
    local body
    body=$(build_epic_body "$feature")

    # Extract labels
    local pillar_labels
    pillar_labels=$(extract_pillar_labels "$spec_content")

    local title="Epic: $feature"

    # Create epic via tracker adapter
    local epic_json
    epic_json=$(tracker_create_epic "$title" "$body" "$pillar_labels")

    _log_creation "$feature" "Created epic: $(echo "$epic_json" | jq -r '.number')"

    echo "$epic_json"
}

create_stories_from_spec() {
    # Create stories linked to epic
    # Arguments: feature_name, epic_json
    # Returns: JSON array of created stories
    local feature="$1"
    local epic_json="$2"

    local spec_content
    spec_content=$(_read_spec "$feature")

    local epic_node_id epic_number
    epic_node_id=$(echo "$epic_json" | jq -r '.node_id')
    epic_number=$(echo "$epic_json" | jq -r '.number')

    # Determine stories to create
    local stories_to_create
    stories_to_create=$(determine_stories "$spec_content" "$feature")

    local created_stories="[]"
    local story_count
    story_count=$(echo "$stories_to_create" | jq 'length')

    for i in $(seq 0 $((story_count - 1))); do
        local story_def
        story_def=$(echo "$stories_to_create" | jq ".[$i]")

        local title story_points story_type
        title=$(echo "$story_def" | jq -r '.title')
        story_points=$(echo "$story_def" | jq -r '.story_points')
        story_type=$(echo "$story_def" | jq -r '.type')

        # Build story body
        local body
        body=$(build_story_body "$story_def" "$epic_number")

        # Create story via tracker adapter
        local story_json
        story_json=$(tracker_create_story "$title" "$body" "$story_type" "$epic_node_id")

        # Set story points
        local story_number
        story_number=$(echo "$story_json" | jq -r '.number')
        tracker_set_story_points "$story_number" "$story_points" > /dev/null 2>&1 || true

        # Add story points to result
        story_json=$(echo "$story_json" | jq --argjson pts "$story_points" '. + {story_points: $pts}')

        created_stories=$(echo "$created_stories" | jq --argjson s "$story_json" '. + [$s]')

        _log_creation "$feature" "Created story #$story_number: $title (${story_points}pts)"
    done

    echo "$created_stories"
}

# =============================================================================
# Integration Functions
# =============================================================================

create_and_plan() {
    # Full orchestration: spec -> epic -> stories -> mapping -> plan
    # Arguments: feature_name
    # Returns: summary of what was created
    local feature="$1"

    # Step 1: Verify spec exists
    if ! _spec_exists "$feature"; then
        echo "Error: Spec not found: $SPECS_DIR/$feature/spec.md" >&2
        return 1
    fi

    # Step 2: Check for approval (optional but noted)
    local approval_file="$SPECS_DIR/$feature/approval.md"
    if [ -f "$approval_file" ]; then
        echo "  Found approval: $approval_file"
    else
        echo "  Note: No approval file found (continuing anyway)"
    fi

    # Step 3: Create epic
    echo "Creating epic..."
    local epic_json
    epic_json=$(create_epic_from_spec "$feature")
    if [ $? -ne 0 ]; then
        echo "Error: Failed to create epic" >&2
        return 1
    fi
    local epic_number
    epic_number=$(echo "$epic_json" | jq -r '.number')
    echo "  Created epic #$epic_number"

    # Step 4: Create stories
    echo "Creating stories..."
    local stories_json
    stories_json=$(create_stories_from_spec "$feature" "$epic_json")
    if [ $? -ne 0 ]; then
        echo "Error: Failed to create stories" >&2
        return 1
    fi
    local story_count
    story_count=$(echo "$stories_json" | jq 'length')
    echo "  Created $story_count stories"

    # Step 5: Generate plan via plan-generator.sh
    if [ -f "$SCRIPT_DIR/plan-generator.sh" ]; then
        echo ""
        echo "Generating execution plan..."
        "$SCRIPT_DIR/plan-generator.sh" generate "$feature" "$epic_json" "$stories_json"
    else
        echo "Warning: plan-generator.sh not found, skipping plan generation" >&2
    fi

    # Step 6: Return summary
    local summary
    summary=$(jq -n \
        --arg feature "$feature" \
        --argjson epic "$epic_json" \
        --argjson stories "$stories_json" \
        --argjson story_count "$story_count" \
        '{
            feature: $feature,
            epic: $epic,
            stories: $stories,
            total_tickets: ($story_count + 1)
        }')

    echo ""
    echo "=========================================="
    echo "COMPLETE: Created $((story_count + 1)) tickets for $feature"
    echo "  Epic: #$epic_number"
    echo "  Stories: $story_count"
    if [ -f "$TICKETS_DIR/${feature}.json" ]; then
        echo "  Mapping: $TICKETS_DIR/${feature}.json"
    fi
    if [ -f "$SPECS_DIR/$feature/PLAN.md" ]; then
        echo "  Plan: $SPECS_DIR/$feature/PLAN.md"
    fi
    echo "=========================================="

    _log_creation "$feature" "Complete: epic=#$epic_number, stories=$story_count"

    # Return success
    return 0
}

# =============================================================================
# Preview Functions
# =============================================================================

preview_tickets() {
    # Show what would be created without creating
    local feature="$1"

    if ! _spec_exists "$feature"; then
        echo "Error: Spec not found: $SPECS_DIR/$feature/spec.md" >&2
        return 1
    fi

    local spec_content
    spec_content=$(_read_spec "$feature")

    echo "=========================================="
    echo "TICKET PREVIEW: $feature"
    echo "=========================================="
    echo ""

    # Epic preview
    local epic_body
    epic_body=$(build_epic_body "$feature")
    local pillar_labels
    pillar_labels=$(extract_pillar_labels "$spec_content")

    echo "EPIC:"
    echo "  Title: Epic: $feature"
    echo "  Labels: specflow:epic,$pillar_labels"
    echo "  Body preview (first 500 chars):"
    echo "  ----------------------------------------"
    echo "${epic_body:0:500}..."
    echo "  ----------------------------------------"
    echo ""

    # Stories preview
    local stories
    stories=$(determine_stories "$spec_content" "$feature")
    local story_count
    story_count=$(echo "$stories" | jq 'length')

    echo "STORIES ($story_count):"
    for i in $(seq 0 $((story_count - 1))); do
        local title story_points story_type
        title=$(echo "$stories" | jq -r ".[$i].title")
        story_points=$(echo "$stories" | jq -r ".[$i].story_points")
        story_type=$(echo "$stories" | jq -r ".[$i].type")

        echo "  $((i + 1)). $title"
        echo "     Type: $story_type"
        echo "     Story Points: $story_points"
    done
    echo ""

    # Wave grouping preview
    echo "WAVE GROUPING (preliminary):"
    echo "  Wave 1 (independent): Backend, Infrastructure"
    echo "  Wave 2 (dependent): Frontend, Testing"
    echo ""

    echo "=========================================="
    echo "Use 'ticket-creator.sh $feature --yes' to create"
    echo "=========================================="
}

# =============================================================================
# CLI Interface
# =============================================================================

show_help() {
    echo "Ticket Creator - Create tickets from approved specs"
    echo ""
    echo "Usage:"
    echo "  ticket-creator.sh <feature>           Create tickets with confirmation"
    echo "  ticket-creator.sh <feature> --yes     Create tickets without confirmation"
    echo "  ticket-creator.sh preview <feature>   Preview without creating"
    echo "  ticket-creator.sh create <feature>    Same as <feature>"
    echo "  ticket-creator.sh --help              Show this help"
    echo ""
    echo "The script reads specs from .specflow/specs/{feature}/spec.md"
    echo "and creates an epic + stories in the configured tracker."
    echo ""
    echo "Examples:"
    echo "  ticket-creator.sh add-logout-button"
    echo "  ticket-creator.sh preview payment-integration"
    echo "  ticket-creator.sh payment-integration --yes"
}

main() {
    local command="${1:-}"
    local feature=""
    local auto_confirm=false

    # Parse arguments
    case "$command" in
        --help|-h)
            show_help
            exit 0
            ;;
        preview)
            feature="${2:-}"
            if [ -z "$feature" ]; then
                echo "Error: Feature name required" >&2
                show_help
                exit 1
            fi
            preview_tickets "$feature"
            exit 0
            ;;
        create)
            feature="${2:-}"
            shift 2 || true
            ;;
        "")
            echo "Error: Feature name required" >&2
            show_help
            exit 1
            ;;
        *)
            feature="$command"
            shift || true
            ;;
    esac

    # Check for --yes flag
    for arg in "$@"; do
        if [ "$arg" = "--yes" ] || [ "$arg" = "-y" ]; then
            auto_confirm=true
        fi
    done

    if [ -z "$feature" ]; then
        echo "Error: Feature name required" >&2
        show_help
        exit 1
    fi

    # Check spec exists
    if ! _spec_exists "$feature"; then
        echo "Error: Spec not found: $SPECS_DIR/$feature/spec.md" >&2
        exit 1
    fi

    # Show preview
    preview_tickets "$feature"
    echo ""

    # Confirm unless --yes
    if [ "$auto_confirm" = false ]; then
        read -rp "Create these tickets? [y/N] " confirm
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 0
        fi
    fi

    echo ""
    echo "Creating tickets..."
    echo ""

    # Use integrated create_and_plan function
    create_and_plan "$feature"
}

# Run main if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
